name: build ios unity plugin

inputs:
  backend:
    description: 'js backend'     
    required: true
  config:
    type: choice
    description: Release Or Debug
    default: 'Release'
    options:
    - Release
    - Debug
  websocket:
    description: enable websocket
    default: '0'
  build_proj_dir:
    description: 'build project dir'     
    required: false
    default: 'native_src'
  GITHUB_TOKEN:
    required:

runs:
  using: "composite"
  steps:
    - name: Build
      shell: bash
      run: |
        cd unity
        npm i
        cd ${{ inputs.build_proj_dir }}
        node ../cli make --platform ios --backend ${{ inputs.backend }} --config ${{ inputs.config }} --websocket ${{ inputs.websocket }}
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        path: ./unity/Assets/core/upm/Plugins/**/*
        name: Unity_Plugins (${{ inputs.backend }}_${{ inputs.config }})
    - name: Clean
      shell: bash
      run: rm -rf ./unity/Assets/core/upm/Plugins/**/*