name: build linux unity plugin

inputs:
  backend:
    description: 'js backend'     
    required: true
  config:
    type: choice
    description: Release Or Debug
    default: 'Release'
    options:
    - Release
    - Debug
  build_proj_dir:
    description: 'build project dir'     
    required: false
    default: 'native_src'
  GITHUB_TOKEN:
    required:

runs:
  using: "composite"
  steps:
    - name: Install libc++-dev
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install clang
        sudo apt-get install build-essential
        sudo apt-get install libc++-dev
        sudo apt-get install libc++abi-dev
    - name: Build
      shell: bash
      run: |
        cd unity
        npm i
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        git pull
        ./emsdk install 3.1.8
        ./emsdk activate 3.1.8
        source ./emsdk_env.sh
        cd ../${{ inputs.build_proj_dir }}
        node ../cli make --platform wasm --arch wasm32 --backend quickjs --config ${{ inputs.config }}
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        path: ./unity/Assets/core/upm/Plugins/**/*
        name: Unity_Plugins (${{ inputs.backend }}_${{ inputs.config }})
    - name: Clean
      shell: bash
      run: rm -rf ./unity/Assets/core/upm/Plugins/**/*
